server.port=8081
spring.application.name=banco-xyz

# Import configuration from Config Server (usa el nombre del servicio: config-server)
spring.config.import=configserver:http://config-server:8888

# Eureka client configuration (usa el nombre del servicio: eureka-server)
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

# Kafka producer configuration (usa el nombre del servicio: kafka)
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
app.kafka.topic.transferencias=banco-xyz.transferencias

# Expose actuator endpoints for verification
management.endpoints.web.exposure.include=*