server.port=8761
spring.application.name=eureka-server

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Make the dashboard available
management.endpoints.web.exposure.include=*
