server.port=8888
spring.application.name=config-server
spring.cloud.config.server.native.searchLocations=classpath:/config-repo,./config-repo
spring.profiles.active=native
management.endpoints.web.exposure.include=*
 
